version: 2.1


executors:

  android:
    docker:
      - image: circleci/android:api-28
    working_directory: ~/rxsmartlock
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx1536m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"


jobs:

  build:
    executor: android
    steps:
      - checkout
      - run: ./gradlew :rxsmartlock:build :rxsmartlock:test :example:assembleDebug :example:testDebug

  deploy:
    executor: android
    steps:
      - checkout
      - run: openssl aes-256-cbc -d -in Freeletics.gpg.enc -out Freeletics.gpg -k $ENCRYPTION_KEY
      - run: gpg --import Freeletics.gpg
      - run: echo "signing.password=$PGP_KEY" >> gradle.properties
      - run: echo "signing.secretKeyRingFile=/home/travis/.gnupg/secring.gpg" >> gradle.properties
      - run: ./gradlew :rxsmartlock:uploadArchives --no-daemon --no-parallel


workflows:

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
